version: "3.3"

services:
    testbot:
        build: .
        restart: always
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        volumes:
            - /usr/src/app/
