# Generated by Django 3.1.1 on 2020-09-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_code_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'Штрих код', 'verbose_name_plural': 'Штрих коды'},
        ),
        migrations.AlterUniqueTogether(
            name='code',
            unique_together={('client', 'code')},
        ),
    ]
