# Generated by Django 3.1.1 on 2020-09-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200913_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='Баллы'),
        ),
    ]
