# Generated by Django 3.1.1 on 2020-09-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_code_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=250, unique=True, verbose_name='Код'),
        ),
    ]
